# Generated by Django 3.2.5 on 2022-07-12 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220712_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='fecha_streno',
            new_name='fecha_estreno',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='sipnopsis',
            new_name='sinopsis',
        ),
    ]
